# Generated by Django 4.2 on 2024-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jinis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloques',
            name='codigo',
        ),
    ]
