# Generated by Django 4.2 on 2024-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_participante_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='asistencia',
            field=models.IntegerField(default=0),
        ),
    ]
